const products = [
    {
        "id": 40,
        "name":" Haier 9140WB Chrome Pro Refrigerator",
        "price": " 67,000",
        "image": "./images/21.png",
        "description": "Experience Efficient Cooling and Smart Use of Space with the Dawlance 9140WB Chrome Pro Refrigerator.Finding a refrigerator that offers efficient cooling in a compact size can be a challenge. Look no further than the Dawlance 9140WB Chrome Pro Refrigerator, available at the best price in Pakistan from AYS Online.",
    },
    {
        "id": 2,
        "name":" Haier SBS 600 Inverter Black GD Refrigerator",
        "price": "328,000",
        "image": "./images/22.png",
        "description": "The new range of SBS 600 models are a perfect blend of technology, aesthetics & food preservation solution, With its biggest capacity and state-of-the-art unique for the first time introduced features this product is fit to meet all your daily requirements and looks great in your living room.",
    },
    {
        "id": 3,
        "name":" Haier 16 CFT Top Mount Refrigerator 9193-LF GD Avante",
        "price": "107,900",
        "image": "images/23.png",
        "description": "Introducing the Dawlance Refrigerator 91999 AVANTE+ IOT ? the epitome of innovation and convenience in the world of refrigeration. At Aysonline, we are thrilled to present this cutting-edge appliance designed to revolutionize your kitchen and elevate your lifestyle.",
    },
    {
        "id": 4,
        "name":"Haier 9122 EDS Top Mount Ac",
        "price": "90,800",
        "image": "images/24.png",
        "description": "The Dawlance Euro Design Series provides the best performance and energy savings With Hybrid Cooling Technology. Power outages are no longer an issue thanks to the four-day cooling retention. This European-standard refrigerator uses 7.90 PKR per day instead of 15.80 PKR per day, saving you money on your monthly electricity bill.",
    },
    {
        "id": 5,
        "name":" Haier X 1 Ton Inverter Split AC",
        "price": "119,999 ",
        "image": "images/25.png",
        "description": "Our Multi-functional Air Conditioners have now got you covered in Summers as well as Winters with Dual Technology of Cooling & Heating with a single touch of a button.",
    },
    {
        "id": 6,
        "name":" Haier 1.5 Ton Silver Inverter Split AC",
        "price":"174,900 ",
        "image": "images/26.png",
        "description": "Our Multi-functional Air Conditioners have now got you covered in Summers as well as Winters with Dual Technology of Cooling & Heating with a single touch of a button.",
    },
    {
        "id": 7,
        "name":" Haier  White Inverter Microwave oven",
        "price": "171,900 ",
        "image": "images/27.png",
        "description": "Our Multi-functional Air Conditioners have now got you covered in Summers as well as Winters with Dual Technology of Cooling & Heating with a single touch of a button.",
    },
    {
        "id": 8,
        "name":"Haier Cool Only Inverter Microwave oven",
        "price": "165,300 ",
        "image": "images/28.png",
        "description": "Our Multi-functional Air Conditioners have now got you covered in Summers as well as Winters with Dual Technology of Cooling & Heating with a single touch of a button.",
    },
    {
        "id": 9,
        "name":" Haier ha-MD10 Washing machine",
        "price": "20,499",
        "image": "images/29.png",
        "description": "Comfort food cravings or late-night snacking, DW-MD 10 is the microwave to satiate your appetite for easy-to-make snacks. From mix vegetable soup, hot coffee, cream caramel to brownies, butter popcorn and tea - DW-MD is the perfect match for the family that never says no to comfort food.",
    },
    {
        "id": 10,
        "name":" Haier 23D Solo Washing Machine",
        "price":"32,500",
        "image": "images/30.png",
        "description": "Comfort food cravings or late-night snacking, DW-MD 10 is the microwave to satiate your appetite for easy-to-make snacks. From mix vegetable soup, hot coffee, cream caramel to brownies, butter popcorn and tea - DW-MD is the perfect match for the family that never says no to comfort food.",
    },
    {
        "id": 11,
        "name":" Haier 20M Solo Washing machine",
        "price": "22,000",
        "image": "images/31.png",
        "description": "Comfort food cravings or late-night snacking, DW-MD 10 is the microwave to satiate your appetite for easy-to-make snacks. From mix vegetable soup, hot coffee, cream caramel to brownies, butter popcorn and tea - DW-MD is the perfect match for the family that never says no to comfort food.",
    },
    {
        "id": 12,
        "name":"Haier HA-131HP UHD Android Tv",
        "price": "38,999",
        "image": "images/32.png",
        "description": "Capacity: 30 Liters Rated Input Power (Microwave): 1450 W Rated Output Power (Microwave): 900 W Rated Input Power (Grill): 1000 W5 Microwave Power Levels Control Panel: Digital Jog Dial with LED Display Deodorizer for Odor Removal Functions:",
    },
    {
        "id": 13,
        "name":" Haier DWF-7120 W 7Kg Front Load",
        "price": "152,999",
        "image": "images/13.png",
        "description": "Regional Wash Programs Stain Buster Technology Hygiene Wash kills upto 99.9 % Bacteria Embroidery Care Program Special Algorithms for Wools Warranty: 10 years inverter Motor Warranty Energy Rating of A+++(-10%).",
    },
    {
        "id": 14,
        "name":" Haier DWF 7200 X  7Kg Fornt ",
        "price": "168,999",
        "image": "images/14.png",
        "description": "Regional Wash Programs Stain Buster Technology Hygiene Wash kills upto 99.9 % Bacteria Embroidery Care Program Special Algorithms for Wools Warranty: 10 years inverter Motor Warranty Energy Rating of A+++(-10%).",
    }
];
export default products;