const products = [
    {
        "id": 1,
        "name":" Dawlance 9140WB Chrome Pro Refrigerator",
        "price": "67,000",
        "image": "./images/1.png",
        "description": "Experience Efficient Cooling and Smart Use of Space with the Dawlance 9140WB Chrome Pro Refrigerator.Finding a refrigerator that offers efficient cooling in a compact size can be a challenge. Look no further than the Dawlance 9140WB Chrome Pro Refrigerator, available at the best price in Pakistan from AYS Online.",
    },
    {
        "id": 2,
        "name":" Dawlance SBS 600 Inverter Black GD Refrigerator",
        "price": "328,000",
        "image": "./images/2.png",
        "description": "The new range of SBS 600 models are a perfect blend of technology, aesthetics & food preservation solution, With its biggest capacity and state-of-the-art unique for the first time introduced features this product is fit to meet all your daily requirements and looks great in your living room.",
    },
    {
        "id": 3,
        "name":" Dawlance 16 CFT Top Mount Refrigerator 9193-LF GD Avante",
        "price": "107,900",
        "image": "images/3.png",
        "description": "Introducing the Dawlance Refrigerator 91999 AVANTE+ IOT ? the epitome of innovation and convenience in the world of refrigeration. At Aysonline, we are thrilled to present this cutting-edge appliance designed to revolutionize your kitchen and elevate your lifestyle.",
    },
    {
        "id": 4,
        "name":"Dawlance 9122 EDS Top Mount Refrigerator",
        "price": "90,800",
        "image": "images/4.png",
        "description": "The Dawlance Euro Design Series provides the best performance and energy savings With Hybrid Cooling Technology. Power outages are no longer an issue thanks to the four-day cooling retention. This European-standard refrigerator uses 7.90 PKR per day instead of 15.80 PKR per day, saving you money on your monthly electricity bill.",
    },
    {
        "id": 5,
        "name":" Enercon X 1 Ton Inverter Split AC",
        "price": "119,999 ",
        "image": "images/5.png",
        "description": "Our Multi-functional Air Conditioners have now got you covered in Summers as well as Winters with Dual Technology of Cooling & Heating with a single touch of a button.",
    },
    {
        "id": 6,
        "name":" Excel 1.5 Ton Silver Inverter Split AC",
        "price":"174,900 ",
        "image": "images/6.png",
        "description": "Our Multi-functional Air Conditioners have now got you covered in Summers as well as Winters with Dual Technology of Cooling & Heating with a single touch of a button.",
    },
    {
        "id": 7,
        "name":" Excel 1.5 Ton White Inverter Split AC",
        "price": "171,900 ",
        "image": "images/7.png",
        "description": "Our Multi-functional Air Conditioners have now got you covered in Summers as well as Winters with Dual Technology of Cooling & Heating with a single touch of a button.",
    },
    {
        "id": 8,
        "name":"Frost 1.5 Ton Cool Only Inverter Split AC",
        "price": "165,300 ",
        "image": "images/8.png",
        "description": "Our Multi-functional Air Conditioners have now got you covered in Summers as well as Winters with Dual Technology of Cooling & Heating with a single touch of a button.",
    },
    {
        "id": 9,
        "name":" Dawlance DW-MD10 Microwave Oven 20L",
        "price": "20,499",
        "image": "images/9.png",
        "description": "Comfort food cravings or late-night snacking, DW-MD 10 is the microwave to satiate your appetite for easy-to-make snacks. From mix vegetable soup, hot coffee, cream caramel to brownies, butter popcorn and tea - DW-MD is the perfect match for the family that never says no to comfort food.",
    },
    {
        "id": 10,
        "name":" Roast 23D Solo Black Oven",
        "price":"32,500",
        "image": "images/10.png",
        "description": "Comfort food cravings or late-night snacking, DW-MD 10 is the microwave to satiate your appetite for easy-to-make snacks. From mix vegetable soup, hot coffee, cream caramel to brownies, butter popcorn and tea - DW-MD is the perfect match for the family that never says no to comfort food.",
    },
    {
        "id": 11,
        "name":" Panini 20M Solo Black Oven",
        "price": "22,000",
        "image": "images/11.png",
        "description": "Comfort food cravings or late-night snacking, DW-MD 10 is the microwave to satiate your appetite for easy-to-make snacks. From mix vegetable soup, hot coffee, cream caramel to brownies, butter popcorn and tea - DW-MD is the perfect match for the family that never says no to comfort food.",
    },
    {
        "id": 12,
        "name":"Dawlance DW-131HP Microwave Oven",
        "price": "38,999",
        "image": "images/12.png",
        "description": "Capacity: 30 Liters Rated Input Power (Microwave): 1450 W Rated Output Power (Microwave): 900 W Rated Input Power (Grill): 1000 W5 Microwave Power Levels Control Panel: Digital Jog Dial with LED Display Deodorizer for Odor Removal Functions:",
    },
    {
        "id": 13,
        "name":" Dawlance DWF-7120 W 7Kg Front Load",
        "price": "152,999",
        "image": "images/13.png",
        "description": "Regional Wash Programs Stain Buster Technology Hygiene Wash kills upto 99.9 % Bacteria Embroidery Care Program Special Algorithms for Wools Warranty: 10 years inverter Motor Warranty Energy Rating of A+++(-10%).",
    },
    {
        "id": 14,
        "name":" Dawlance DWF 7200 X Inverter 7Kg Fornt ",
        "price": "168,999",
        "image": "images/14.png",
        "description": "Regional Wash Programs Stain Buster Technology Hygiene Wash kills upto 99.9 % Bacteria Embroidery Care Program Special Algorithms for Wools Warranty: 10 years inverter Motor Warranty Energy Rating of A+++(-10%).",
    },
    {
        "id": 15,
        "name":" Dawlance DWT 270 S LVS+ 12Kg Top Load",
        "price": "100,999",
        "image": "images/15.png",
        "description": "Official Warranty Large Capacity for Broad House holdGlass DoorLVS can operate at a voltage as low as 150 Volts Saves up to 38% Energy Triple Water fall Technology Extreme Plus Air Dryer Pro Fabric Drum Warranty:year parts + 3 Years + 10 years Motor Warranty",
    },
    {
        "id": 16,
        "name":"Dawlance DWT-1167 FLP 12Kg Top Load",
        "price": "81,999",
        "image": "images/16.png",
        "description": "Official Warranty Large Capacity for Broad House holdGlass DoorLVS can operate at a voltage as low as 150 Volts Saves up to 38% Energy Triple Water fall Technology Extreme Plus Air Dryer Pro Fabric Drum Warranty:year parts + 3 Years + 10 years Motor Warranty.",
    },
    {
        "id": 17,
        "name":" Dawlance E3A 32 Inch Spectrum",
        "price": "39,999",
        "image": "images/17.png",
        "description": "Resolution: 1920 x 1080 ,Screen Type: Narrow Bezel (Frameless) ,Turbo Sound:16 W .HDMI:2 ,USB:1 2 Years ( Panel, Parts, Or Home Service, Except Breakage of Panel and Electric Spark or Burnt)",
    },
    {
        "id": 18,
        "name":" Dawlance 43″ 43G3AP 4K UHD Android LED",
        "price": " 81,000",
        "image": "images/18.png",
        "description": "Resolution: 1920 x 1080 ,Screen Type: Narrow Bezel (Frameless) ,Turbo Sound:16 W .HDMI:2 ,USB:1 2 Years ( Panel, Parts, Or Home Service, Except Breakage of Panel and Electric Spark or Burnt).",
    },
    {
        "id": 19,
        "name":" Dawlance 43″ 43G3AP 4K UHD Android LED",
        "price": "81,000",
        "image": "images/19.png",
        "description": "Resolution: 1920 x 1080 ,Screen Type: Narrow Bezel (Frameless) ,Turbo Sound:16 W .HDMI:2 ,USB:1 2 Years ( Panel, Parts, Or Home Service, Except Breakage of Panel and Electric Spark or Burnt).",
    },
    {
        "id": 20,
        "name":"Dawlance E22 32 Inch Blaze Series 2K  ",
        "price": "47,499",
        "image": "images/20.png",
        "description": "Resolution: 1920 x 1080 ,Screen Type: Narrow Bezel (Frameless) ,Turbo Sound:16 W .HDMI:2 ,USB:1 2 Years ( Panel, Parts, Or Home Service, Except Breakage of Panel and Electric Spark or Burnt).",
    }

];
export default products;